server:
  port: 9002
spring:
  application:
    name: article-server
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
feign:
  client:
    config:
      user-server:
        logger-level: FULL
  hystrix:
    enabled: true
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 1000